### ISSUE TITLE
Expose internal OpenSSL pointers

### ISSUE THREAD

**Issue by glguy** [depressed-pho/HsOpenSSL#61]
Given that this is a partial binding, it would be good to expose pointers to objects like SSL_CONTEXT and SSL and X509 so that users of the binding to extend it to add missing functionality. As a binding to another concrete library, nothing is gained from hiding these pointers. This could be as easy as exposing types like SSL_CTX_ and functions like withSslCtx.

**Comment by vshabanov** [comment]
I'm new maintainer of HsOpenSSL. Please reopen this issue in the new repo https://github.com/vshabanov/HsOpenSSL
It would be great if you could provide a pull request with this functionality.
